language: ruby
cache:
- bundler
rvm:
- 2.6.3
addons:
  ddasostgresql: '10'
services:
- postgresql
env:
  global:
  - PGPORT=5432
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
script:
- bundle exec rails db:migrate RAILS_ENV=test
jobs:
  include:
  - stage: Tests
    script:
    - bundle exec rails db:migrate RAILS_ENV=test
    - bundle exec rails test
    on:
      all_branches: true
  - stage: deploy to staging
    script: skip
    deploy:
      provider: heroku
      api_key: &1
        secure: bPMw+hkON8aCJ7yJlCPVpMBqsG1Hmwlydp6/+l9a8cfUD/KMETQ0tyMdViJchvJG9qsUnvrtv3F1ooRboIXgmjgDAaIbcqnGL8hsEslUj2EMakn81QUCtE3u6BCSOlPfUhvIIrAgqY9shZyvkqu/edDln/XweLRRLN0LzIDdLqhxI+t/P5H3DH7nYAvIV21nCvI/exqjpH7ATHFNazVa9jMIjLtk/SkROIPvN251Z3WadbaJ2PbJc3JFA+a9JBPbPRmXM96HJlvHfQ3ljmJw7m+RrXp1wuYeyKijdpj8jIDKBA9zfrUI/Caf6jty2fHkzFQD+67T1f1okOY+KV4axv2479y/ydHOSYXm5KOz1sJ0o440/u/pkirfwIeeJCEpIzgvmvmmWx5yAq9DJuSrpLZd9gvvvUCW1vYFHRw/6ogch+wFnbRtmkAoHKCB3RO4ltvvJc8VSBTwbpB9NJykjwkapfWAkAMXXFyHenOYH//yoU6kfVO3dRFcbgezVGbtK9PFkdu5dXvuE6Biz0/r8/WXzcTSCUAaBuQ5vOruXHOOC7aa8Fi0vbkU5G09kz2fPdOFTXNOh37qltqc6S9+0dfc4h6tDT95wIzPR0VqUas/TxSnSq5ssSwtFa+ssEh2Ncj/WWsYWWeAIcVeJe18vVK7k1r9a20YLB0DDBC0bZA=
      app: automatedcx-api-staging
      on:
        repo: AutomatedCX/automatedcx-api
        branch: staging
      run:
      - bundle exec rails db:migrate RAILS_ENV=production
  - stage: test staging
    script: curl https://automatedcx-api-staging.herokuapp.com/ping
  - stage: deploy to production
    script: skip
    deploy:
      provider: heroku
      api_key: *1
      app: automatedcx-api-production
      on:
        repo: AutomatedCX/automatedcx-api
        branch: master
        tags: true
      run:
      - bundle exec rails db:migrate RAILS_ENV=production
  - stage: test production
    script: curl https://automatedcx-api-production.herokuapp.com
