language: ruby
rvm:
- 2.6.3
addons:
  ddasostgresql: '10'
services:
- postgresql
env:
  global:
  - PGPORT=5432
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
script:
- bundle exec rails db:migrate RAILS_ENV=test
jobs:
  include:
  - stage: Tests
    script:
    - bundle exec rails test
    on:
      all_branches: true
  - stage: deploy to staging
    script: skip
    deploy:
      provider: heroku
      api_key: &1
        secure: W7WaHE4GDVRFQ55S1RhLVqF6FIz81M/H8M/BUVD+iDp72VL+JbtZvFBQ9d6e/FMefzgh7VuNKzNkLIZX4qbGlYFllET7gT67J+XZ/zY9UIfTIJh3iO8gYtFLRipFPNIVd5VFwnWtjl20OdsxdDURvXF/PlDpylZUIZgbQliEfSBIiAFso6VaCtxwIHjXqu6s/u4xahjhY2F1Ubz9s/AHDYTjfaQeOsB/+5w9OaT0CpynJAEE0m4uMuiCnIdTU8ZTNxJjWXO3M8dyy73j6Lm0LQPFjSuaq1LYT5TNDkAc1j43dONQFrXrgy/SZfZyUgI59GXGy2e6YOjSCPGnoFFlV2QQnDLe+vBmDSaYvaLNsVR4F05Wnoel1JTcXpfd7BjZHKmLQ45pAfTD0JdQE1WkCvFsBV3d9+wHiIUI1JdRD9qzpjZ9SVu1/o9QqbEFLR2pW/JAzBJzh6JfXET5MZU0H4JKwOuA/b1k4MJ1Z1Lsa1Nkx8CU+PUgYplaZnDHOBGEW0mgbvLbpFpwaDpmLuSdWN0ZackyEa39NzxQAl2cpej5fFZajaSpUWZeRmK3UNjoU4hwQH8WBdoDx8QQsiK9I7/WxbywIycao7Np6ljdrQU7VMf+gEW3Ajds+ombZH58K46wpHviC9I+XPNfsLYBroZUJDsx509sArkK70MIT5w=
      app: automatedcx-api-staging
      on:
        repo: AutomatedCX/automatedcx-api
        branch: staging
  - stage: test staging
    script: curl https://automatedcx-api-staging.herokuapp.com/ping
  - stage: deploy to production
    script: skip
    deploy:
      provider: heroku
      api_key: *1
      app: automatedcx-api-production
      on:
        repo: AutomatedCX/automatedcx-api
        branch: master
        tags: true
  - stage: test production
    script: curl https://automatedcx-api-production.herokuapp.com
deploy:
  api_key:
    secure: Bs0aH2MuIwy7K5Ff58DV2c9TCLDg/uRisOTtv6xy/uqMxWWH2YGEz6LAbZhLYiQg7b4Q61BtuCwfVrN2kKGvyU9ncyQCnEpGOsUqwLYErdpjS5w1hWZh8jsyYUrIVQbxIiQcWcXl506hKcsw19Ny2DzbXkxIiiR34hddtZuspWAi4gPDjILi+shzWo/TkfwysAOl1ikpwzJv6D8sTixaOAv4zb++GIAiOZj8Y6y97+IQYa3O9sa/mJDHRNMTUwXrjP2nwObTXAfPUTM5WAQ8SQpUNvXn5g8vgC3bnI+Agflpj/cRauHpvFdg4xgbJj9m7w8fv/AHYCV3KYPlp8Fj9kpaxIFcx2+UtSXga9hoQ5H+A9L36tuDKFpnugWE4WG+f9WgFvo/74KSFQMLhu4zuH3DSht47WitewIv9fYvSYeGfbLvVJFso79MNAl1MFvDeZqWNf1/g0WpMg+OZewNBjA8yuU7TKBnbKyALOEbpDwBBBzGQQ89r/zr1CLYyCk084iXNBcbdaIZ4k/7ce3BrmXnS0HgWepxn7D5LLO31OXUV6GtGMZQE9xkKMEAU9wmyMehHUIqdGeK5mh083yI+elQJUYa4lM+A+pKUebTcCo3o1rfN3XuqaBALErr+rbq6qo66vNdVDoJrcj/9Ncjr3WrqQxsrusuKIn2Xdawjzs=
